defaults: &default
  api_url:       'http://api.openweathermap.org/data/2.5/weather'
  temp_units:    'imperial'
  cache_minutes: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
